### ISSUE TITLE
查询遗器数据和实际数据不匹配

### ISSUE THREAD

**Issue by Ocetars** [baiqwerdvd/StarRailUID#19]
具体表现为主词条正确，副词条属性正确但是数据错误

**Comment by baiqwerdvd** [comment]
更新依赖，应该修了

**Comment by Ocetars** [comment]
> 更新依赖，应该修了

已解决

**Comment by Ocetars** [comment]
> 更新依赖，应该修了

更新后有变化，但还是有些对不上
速度双爆命中抵抗击破数值正确，生命攻击防御不正确
![Image_1722595163491.jpg](https://github.com/user-attachments/assets/a57b8ddb-f9dc-4fc1-89ba-9a5c7452f679)

**Comment by mengluo04** [comment]
> 晚点我再看看~

现在也是错的

**Comment by Ocetars** [comment]
目前只有生命攻击防御的数据不对，佬可以抽空看看吗 @baiqwerdvd

**Comment by mengluo04** [comment]
> 目前只有生命攻击防御的数据不对，佬可以抽空看看吗 @baiqwerdvd

看了下代码，定义了第三方接口都没用，既没有用mihomo的数据，也没有用hakusin的 数据，数据是把hakusin的保存成json存贷本地json文件，然后去里面读，但是计算公式没太看懂，直接用mihomo的数据多方便的

**Comment by mengluo04** [comment]
> 目前只有生命攻击防御的数据不对，佬可以抽空看看吗 @baiqwerdvd

看了下代码，学艺不精没看懂

**Comment by baiqwerdvd** [comment]
试着更新一下依赖呢，随便看了看，修了点bug

**Comment by baiqwerdvd** [comment]
来点图看看

**Comment by mengluo04** [comment]
> 来点图看看

我的问题，忘了升级过光锥，和之前的图拿来对比了。
看了下米游社，数据对的上
大佬牛批
