### ISSUE TITLE
[bug]使用sruid绑定uid提示绑定设备

### ISSUE THREAD

**Issue by mengluo04** [baiqwerdvd/StarRailUID#20]
根据gscore文档找到绑定设备app页面，action最新是5月前构建，apk已失效无法下载

**Comment by Jerry-FaGe** [comment]
![image](https://github.com/user-attachments/assets/a8be73e9-5f37-4da1-a659-4e8cd1ec3a4b)

**Comment by mengluo04** [comment]
> ![image](https://private-user-images.githubusercontent.com/40235071/356054268-a8be73e9-5f37-4da1-a659-4e8cd1ec3a4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODU1ODYsIm5iZiI6MTcyMzA4NTI4NiwicGF0aCI6Ii80MDIzNTA3MS8zNTYwNTQyNjgtYThiZTczZTktNWYzNy00ZGExLWE2NTktNGU4Y2QxZWMzYTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAyNDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYmU1ZjEwZGE0Y2RkN2MyOTY3Mjc2NWM3YzZiMWMzYzcxM2FhMzI5MmIxMDE0ZDI3ZmMxM2I1ODAxMWQyZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tn3y5otaSfIFoM4yrjjCq7wz2bCR6XKXMZVXwjYAVOk)

感谢，只看到action就去找了
