### ISSUE TITLE
【功能建议】抽卡记录是否可以实现自动获取

### ISSUE THREAD

**Issue by mengluo04** [baiqwerdvd/StarRailUID#21]
genshinuid和zzzuid都可以通过sk获取authtoken来生成链接

**Comment by baiqwerdvd** [comment]
sr里面无法这样获取

**Comment by jiluoQAQ** [comment]
你肯定可以的，相信你

**Comment by mengluo04** [comment]
> 你肯定可以的，相信你

我只是个废物，我可不行

**Comment by mengluo04** [comment]
> 你肯定可以的，相信你

试了。。生成的key提示错误，但是看云崽那边的星铁也是用的这个接口开生成，参数有一点点变化，没看透

**Comment by baiqwerdvd** [comment]
嘶，星铁应该是不能实现sk获取authtoken的吧

**Comment by mengluo04** [comment]
> 嘶，星铁应该是不能实现sk获取authtoken的吧

我不到啊，看着个好像是可以，但是我生成出来的不对，怀疑人生.jpg
https://github.com/TsukinaKasumi/StarRail-plugin/blob/main/utils/authkey.js

**Comment by baiqwerdvd** [comment]
应该是能生成不能用

**Comment by mengluo04** [comment]
> 应该是能生成不能用

看起来是，刚去启动了云崽那边，重新看了下sr插件的代码，只是定义了getAuthKey的方法，没有调用，这下死心了
