### ISSUE TITLE
【建议】开放配置允许设置自建mihomo代理

### ISSUE THREAD

**Issue by mengluo04** [baiqwerdvd/StarRailUID#25]
mihomo.me是使用cf解析的，有连接失败的情况，自建代理可以解决这个问题

**Comment by baiqwerdvd** [comment]
@lulu666lulu

**Comment by lulu666lulu** [comment]
你自己找个服务器代理一下不就好了（

**Comment by mengluo04** [comment]
> 你自己找个服务器代理一下不就好了（
我有建好的代理服务，但是
代码里是写死的地址，我总不能手动改吧，改了git pull会有冲突（）
`
async def get_char_card_info(uid: str) -> MihomoData:
    async with AsyncClient(
        base_url='http://api.mihomo.me',
        headers=_HEADER,
        timeout=30,
    ) as client:
        req = await client.get(f'/sr_info/{uid}')
        path = PLAYER_PATH / str(uid)
        path.mkdir(parents=True, exist_ok=True)
        with Path.open(path / f'{uid!s}.json', 'w') as file:
            file.write(req.text)
        return convert(req.json(), type=MihomoData)
`
