### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by dwsxx1** [baiqwerdvd/StarRailUID#40]
![CA251C3324A990E4607A2348307C55F2](https://github.com/user-attachments/assets/512f3099-4b4d-49c9-826a-1d7a7940e084)
![25606890E1C597D3C0B8215122493F2D](https://github.com/user-attachments/assets/2789d73c-e614-4483-85cf-cb527adcc2b1)
已使用sr下载全部资源，显示要安装的依赖我看了是有的，版本也正确

**Comment by KimigaiiWuyi** [comment]
应该已修复

**Comment by dwsxx1** [comment]
谢谢大佬

**Comment by dwsxx1** [comment]
对了，星铁的这个插件好像没有自主刷新抽卡记录功能，只能自己导入记录是吗

**Comment by baiqwerdvd** [comment]
> 对了，星铁的这个插件好像没有自主刷新抽卡记录功能，只能自己导入记录是吗

星铁不能实现自动刷新
