### ISSUE TITLE
查询面板或者刷新面板的时候会出现1313错误

### ISSUE THREAD

**Issue by 811627965** [baiqwerdvd/StarRailUID#45]
部分用户在查询面板的时候会有这个问题，该如何解决
![image](https://github.com/user-attachments/assets/d1f6d383-78e0-46e1-9649-4c7f1499a36e)
![image](https://github.com/user-attachments/assets/c523590f-aff8-4865-8fd2-a10b4bf5575e)

**Comment by baiqwerdvd** [comment]
更新依赖可解决
