### ISSUE TITLE
另开 sruid 专属推送表

### ISSUE THREAD

**Issue by Jerry-FaGe** [baiqwerdvd/StarRailUID#7]
老仓库有个打算开 sruid 专属推送表的 issue 来着，内容大概是现在推送表跟 gs 的放一起有歧义不好维护吧啦吧啦的，先写过来做个提醒。

另外感觉可以跟 core 那边知会一下把这两个没啥用的配置删了吧，之前做过测试开不开启没什么影响。

![image](https://github.com/baiqwerdvd/StarRailUID/assets/40235071/780d5155-b19b-43de-980b-e6db1b7549b8)

**Comment by baiqwerdvd** [comment]
#33
